### ISSUE TITLE
RSM - <before/> should respond with the last page in the result set

### ISSUE THREAD

**Issue by kevb** [kongo2002/ejabberd-mod-mam#3]
I realise that xep-0059 (RSM) isn't fully implemented yet, but I was hoping you could find your way to fixing this for me. I tried to do it myself but got a little stuck with the Erlang : )

[xep-0059 (RSM) says](http://xmpp.org/extensions/xep-0059.html#last) that a request with an empty &lt;before/&gt; tag should return the last page of results. In mod_mam right now this is an invalid element (if I read correctly).

Mod_mam should return the last page of results when an empty &lt;before/&gt; tag is specified in the query.

Thanks : )

**Comment by kongo2002** [comment]
There were some maybe related issues with the *RSM* handling (see #6) that I just fixed.
