### ISSUE TITLE
how to configure 

### ISSUE THREAD

**Issue by bskoztrk** [kongo2002/ejabberd-mod-mam#8]
i installed ejabberd-mod-mam, 
and add this in /etc/ejabberd/ejabberd.cfg. but its failed how to fix this?
{modules,
  [
    {mod_mam,
      [
        % configure a named replica set and a list of nodes
        {mongo, {<<"rs">>, [{localhost, 27017}, {localhost, 27018}]}},

        % ...
      ]
    },

    % ...
  ]
}.

**Comment by kongo2002** [comment]
Please see the [README](https://github.com/kongo2002/ejabberd-mod-mam/blob/master/README.markdown) for configuration hints. Otherwise I need more information what exactly fails.
